import { FilterEl1, FilterEl2, FilterEl3, FilterEl4, FilterEl5, FilterEl6 } from "./icons";

export const categories = [
  { _id: "1", title: "Shtëpi me qera", icon: FilterEl1 },
  { _id: "2", title: "Prona imobilare", icon: FilterEl2 },
  { _id: "3", title: "Ambiente biznesi me qera", icon: FilterEl3 },
  { _id: "4", title: "Ambiente biznesi në shitje", icon: FilterEl4 },
  { _id: "5", title: "Truall ose tokë", icon: FilterEl5 },
  { _id: "6", title: "Kërkesa për shtëpi", icon: FilterEl6 },
];
export const colors = [
  { _id: "1", title: "#e4f78f" },
  { _id: "2", title: "#eddb15" },
  { _id: "3", title: "#eda115" },
  { _id: "4", title: "#d15e1f" },
  { _id: "5", title: "#d11f1f" },
]
export const furnishing = [
  { _id: "E pamobiluar", title: "E pamobiluar" },
  { _id: "Pjesërisht e mobiluar", title: "Pjesërisht e mobiluar" },
  { _id: "E mobiluar", title: "E mobiluar" },
];
export const structures = [
  { _id: "1", title: "Apartament" },
  { _id: "2", title: "Papafingo" },
  { _id: "3", title: "Penthouse" },
  { _id: "4", title: "Duplex" },
  { _id: "5", title: "Shtëpi private" },
  { _id: "6", title: "Vila luksoze" },
];
export const countries = [
  { _id: "1", title: "Shqipëri" },
  { _id: "2", title: "Kosovë" },
  { _id: "3", title: "Maqedoni" },
];
export const cities = [
  { _id: "1", title: "Tiranë", countryId: "1" },
  { _id: "2", title: "Durrës", countryId: "1" },
  { _id: "3", title: "Shkodër", countryId: "1" },
  { _id: "4", title: "Elbasan", countryId: "1" },
  { _id: "5", title: "Vlorë", countryId: "1" },
  { _id: "6", title: "Korçë", countryId: "1" },
  { _id: "7", title: "Fier", countryId: "1" },
  { _id: "8", title: "Berat", countryId: "1" },
  { _id: "9", title: "Lushnje", countryId: "1" },
  { _id: "10", title: "Pogradec", countryId: "1" },
  { _id: "11", title: "Kavajë", countryId: "1" },
  { _id: "12", title: "Laç", countryId: "1" },
  { _id: "13", title: "Lezhë", countryId: "1" },
  { _id: "14", title: "Kukës", countryId: "1" },
  { _id: "15", title: "Gjirokastër", countryId: "1" },
  { _id: "16", title: "Patos", countryId: "1" },
  { _id: "17", title: "Krujë", countryId: "1" },
  { _id: "18", title: "Kuçovë", countryId: "1" },
  { _id: "19", title: "Sarandë", countryId: "1" },
  { _id: "20", title: "Peshkopi", countryId: "1" },
  { _id: "21", title: "Burrel", countryId: "1" },
  { _id: "22", title: "Cërrik", countryId: "1" },
  { _id: "23", title: "Çorovodë", countryId: "1" },
  { _id: "24", title: "Shijak", countryId: "1" },
  { _id: "25", title: "Librazhd", countryId: "1" },
  { _id: "26", title: "Tepelenë", countryId: "1" },
  { _id: "27", title: "Gramsh", countryId: "1" },
  { _id: "28", title: "Poliçan", countryId: "1" },
  { _id: "29", title: "Bulqizë", countryId: "1" },
  { _id: "30", title: "Përmet", countryId: "1" },
  { _id: "31", title: "Fushë-Krujë", countryId: "1" },
  { _id: "32", title: "Kamëz", countryId: "1" },
  { _id: "33", title: "Rrëshen", countryId: "1" },
  { _id: "34", title: "Ballsh", countryId: "1" },
  { _id: "35", title: "Mamurras", countryId: "1" },
  { _id: "36", title: "Bajram Curri", countryId: "1" },
  { _id: "37", title: "Ersekë", countryId: "1" },
  { _id: "38", title: "Peqin", countryId: "1" },
  { _id: "39", title: "Divjakë", countryId: "1" },
  { _id: "40", title: "Selenicë", countryId: "1" },
  { _id: "41", title: "Bilisht", countryId: "1" },
  { _id: "42", title: "Roskovec", countryId: "1" },
  { _id: "43", title: "Këlcyrë", countryId: "1" },
  { _id: "44", title: "Pukë", countryId: "1" },
  { _id: "45", title: "Memaliaj", countryId: "1" },
  { _id: "46", title: "Rrogozhinë", countryId: "1" },
  { _id: "47", title: "Urë Vajgurore", countryId: "1" },
  { _id: "48", title: "Himarë", countryId: "1" },
  { _id: "49", title: "Delvinë", countryId: "1" },
  { _id: "50", title: "Vorë", countryId: "1" },
  { _id: "51", title: "Koplik", countryId: "1" },
  { _id: "52", title: "Maliq", countryId: "1" },
  { _id: "53", title: "Përrenjas", countryId: "1" },
  { _id: "54", title: "Shtërmen", countryId: "1" },
  { _id: "55", title: "Krumë", countryId: "1" },
  { _id: "56", title: "Libohovë", countryId: "1" },
  { _id: "57", title: "Orikum", countryId: "1" },
  { _id: "58", title: "Fushë-Arrëz", countryId: "1" },
  { _id: "59", title: "Shëngjin", countryId: "1" },
  { _id: "60", title: "Rubik", countryId: "1" },
  { _id: "61", title: "Milot", countryId: "1" },
  { _id: "62", title: "Leskovik", countryId: "1" },
  { _id: "63", title: "Konispol", countryId: "1" },
  { _id: "64", title: "Krastë", countryId: "1" },
  { _id: "65", title: "Kërrabë", countryId: "1" },
  { _id: "66", title: "Përmet", countryId: "1" },
  { _id: "67", title: "Skrapar", countryId: "1" },
  { _id: "68", title: "Tropojë", countryId: "1" },
];
export const zones = [
  { _id: "1", title: "Kombinat", cityId: "1" },
  { _id: "2", title: "Rruga e Kavajës", cityId: "1" },
  { _id: "3", title: "Ali Demi", cityId: "1" },
  { _id: "4", title: "Blloku", cityId: "1" },
  { _id: "5", title: "Astiri", cityId: "1" },
  { _id: "6", title: "Brryli", cityId: "1" },
  { _id: "7", title: "Don Bosko", cityId: "1" },
  { _id: "8", title: "Himarë", cityId: "1" },
  { _id: "9", title: "Kamëz", cityId: "1" },
  { _id: "10", title: "Paskuqan", cityId: "1" },
  { _id: "12", title: "Komuna e Parisit", cityId: "1" },
  { _id: "13", title: "Laprakë", cityId: "1" },
  { _id: "14", title: "Kopshti Botanik", cityId: "1" },
  { _id: "15", title: "Kopshti Zoologjik", cityId: "1" },
  { _id: "16", title: "Liqeni i Thatë", cityId: "1" },
  { _id: "17", title: "Rruga e Durrësit", cityId: "1" },
  { _id: "18", title: "Stacioni i Trenit", cityId: "1" },
  { _id: "19", title: "5 Maji", cityId: "1" },
  { _id: "20", title: "Qyteti Studenti", cityId: "1" },
  { _id: "21", title: "Sauk i Ri", cityId: "1" },
  { _id: "22", title: "Sauk i Vjetër", cityId: "1" },
  { _id: "23", title: "Rolling Hills", cityId: "1" },
  { _id: "24", title: "Fresku", cityId: "1" },
  { _id: "25", title: "Currila", cityId: "2" },
  { _id: "26", title: "Gjiri i Lalëzit", cityId: "2" },
  { _id: "27", title: "Golem", cityId: "2" },
  { _id: "28", title: "Shkëmbi i Kavajës", cityId: "2" },
  { _id: "29", title: "Plepa", cityId: "2" },
  { _id: "30", title: "Qendër", cityId: "2" },
  { _id: "31", title: "Zona Periferike", cityId: "2" },
  { _id: "32", title: "Velipojë", cityId: "3" },
  { _id: "33", title: "Shirokë", cityId: "3" },
  { _id: "34", title: "Qendër", cityId: "3" },
  { _id: "35", title: "Zona Periferike", cityId: "3" },
  { _id: "36", title: "Qendër", cityId: "20" },
  { _id: "37", title: "Zona Periferike", cityId: "20" },
  { _id: "38", title: "Borsh", cityId: "28" },
  { _id: "39", title: "Dhërmi", cityId: "28" },
  { _id: "40", title: "Jalë", cityId: "28" },
  { _id: "41", title: "Livadh", cityId: "28" },
  { _id: "42", title: "Palasë", cityId: "28" },
  { _id: "43", title: "Potam", cityId: "28" },
  { _id: "44", title: "Qeparo", cityId: "28" },
  { _id: "45", title: "Vuno", cityId: "28" },
  { _id: "46", title: "Zona Periferike", cityId: "28" },
  { _id: "47", title: "Qendër", cityId: "4" },
  { _id: "48", title: "Zona Periferike", cityId: "4" },
  { _id: "49", title: "Kuçovë", cityId: "8" },
  { _id: "50", title: "Qendër", cityId: "8" },
  { _id: "51", title: "Zona Periferike", cityId: "8" },
  { _id: "52", title: "Kodra", cityId: "19" },
  { _id: "53", title: "Ksamil", cityId: "19" },
  { _id: "54", title: "Lukovë", cityId: "19" },
  { _id: "55", title: "Qafa e Gjashtës", cityId: "19" },
  { _id: "56", title: "Qendër", cityId: "19" },
  { _id: "57", title: "Zona Periferike", cityId: "19" },
  { _id: "58", title: "Llogara", cityId: "5" },
  { _id: "59", title: "Lungomare", cityId: "5" },
  { _id: "60", title: "Nartë", cityId: "5" },
  { _id: "61", title: "Orikum", cityId: "5" },
  { _id: "63", title: "Plazhi i Vjetër", cityId: "5" },
  { _id: "62", title: "Radhimë", cityId: "5" },
  { _id: "64", title: "Uji i Ftohtë", cityId: "5" },
  { _id: "65", title: "Qendër", cityId: "5" },
  { _id: "66", title: "Zvërnec", cityId: "5" },
  { _id: "67", title: "Zona Periferike", cityId: "5" },
  { _id: "68", title: "Qendër", cityId: "11" },
  { _id: "69", title: "Qerret", cityId: "11" },
  { _id: "70", title: "Spille", cityId: "11" },
  { _id: "71", title: "Zona Periferike", cityId: "11" },
];
