import {
  FilterEl1,
  FilterEl2,
  FilterEl3,
  FilterEl4,
  FilterEl5,
  FilterEl6,
} from "./icons";

export const categories = [
  { _id: "1", category: "Shtëpi me qera", icon: FilterEl1 },
  { _id: "2", category: "Prona imobilare", icon: FilterEl2 },
  { _id: "3", category: "Ambiente biznesi me qera", icon: FilterEl3 },
  { _id: "4", category: "Ambiente biznesi në shitje", icon: FilterEl4 },
  { _id: "5", category: "Truall ose tokë", icon: FilterEl5 },
  { _id: "6", category: "Kërkesa për shtëpi", icon: FilterEl6 },
];
export const structures = [
  { _id: "1", structure: "Apartament" },
  { _id: "2", structure: "Papafingo"},
  { _id: "3", structure: "Penthouse"},
  { _id: "4", structure: "Duplex"},
  { _id: "5", structure: "Shtëpi private"},
  { _id: "6", structure: "Vila luksoze"},
];
export const countries = [
  { _id: "1", country: "Shqipëri" },
  { _id: "2", country: "Kosovë" },
  { country: "Maqedoni", _id: "3" },
];
export const cities = [
  { _id: "1", city: "Tiranë", countryId: "1" },
  { _id: "2", city: "Durrës", countryId: "1" },
  { _id: "3", city: "Shkodër", countryId: "1" },
  { _id: "4", city: "Elbasan", countryId: "1" },
  { _id: "5", city: "Vlorë", countryId: "1" },
  { _id: "6", city: "Korçë", countryId: "1" },
  { _id: "7", city: "Fier", countryId: "1" },
  { _id: "8", city: "Berat", countryId: "1" },
  { _id: "9", city: "Lushnje", countryId: "1" },
  { _id: "10", city: "Pogradec", countryId: "1" },
  { _id: "11", city: "Kavajë", countryId: "1" },
  { _id: "12", city: "Laç", countryId: "1" },
  { _id: "13", city: "Lezhë", countryId: "1" },
  { _id: "14", city: "Kukës", countryId: "1" },
  { _id: "15", city: "Gjirokastër", countryId: "1" },
  { _id: "16", city: "Patos", countryId: "1" },
  { _id: "17", city: "Krujë", countryId: "1" },
  { _id: "18", city: "Kuçovë", countryId: "1" },
  { _id: "19", city: "Sarandë", countryId: "1" },
  { _id: "20", city: "Peshkopi", countryId: "1" },
  { _id: "21", city: "Burrel", countryId: "1" },
  { _id: "22", city: "Cërrik", countryId: "1" },
  { _id: "23", city: "Çorovodë", countryId: "1" },
  { _id: "24", city: "Shijak", countryId: "1" },
  { _id: "25", city: "Librazhd", countryId: "1" },
  { _id: "26", city: "Tepelenë", countryId: "1" },
  { _id: "27", city: "Gramsh", countryId: "1" },
  { _id: "28", city: "Poliçan", countryId: "1" },
  { _id: "29", city: "Bulqizë", countryId: "1" },
  { _id: "30", city: "Përmet", countryId: "1" },
  { _id: "31", city: "Fushë-Krujë", countryId: "1" },
  { _id: "32", city: "Kamëz", countryId: "1" },
  { _id: "33", city: "Rrëshen", countryId: "1" },
  { _id: "34", city: "Ballsh", countryId: "1" },
  { _id: "35", city: "Mamurras", countryId: "1" },
  { _id: "36", city: "Bajram Curri", countryId: "1" },
  { _id: "37", city: "Ersekë", countryId: "1" },
  { _id: "38", city: "Peqin", countryId: "1" },
  { _id: "39", city: "Divjakë", countryId: "1" },
  { _id: "40", city: "Selenicë", countryId: "1" },
  { _id: "41", city: "Bilisht", countryId: "1" },
  { _id: "42", city: "Roskovec", countryId: "1" },
  { _id: "43", city: "Këlcyrë", countryId: "1" },
  { _id: "44", city: "Pukë", countryId: "1" },
  { _id: "45", city: "Memaliaj", countryId: "1" },
  { _id: "46", city: "Rrogozhinë", countryId: "1" },
  { _id: "47", city: "Urë Vajgurore", countryId: "1" },
  { _id: "48", city: "Himarë", countryId: "1" },
  { _id: "49", city: "Delvinë", countryId: "1" },
  { _id: "50", city: "Vorë", countryId: "1" },
  { _id: "51", city: "Koplik", countryId: "1" },
  { _id: "52", city: "Maliq", countryId: "1" },
  { _id: "53", city: "Përrenjas", countryId: "1" },
  { _id: "54", city: "Shtërmen", countryId: "1" },
  { _id: "55", city: "Krumë", countryId: "1" },
  { _id: "56", city: "Libohovë", countryId: "1" },
  { _id: "57", city: "Orikum", countryId: "1" },
  { _id: "58", city: "Fushë-Arrëz", countryId: "1" },
  { _id: "59", city: "Shëngjin", countryId: "1" },
  { _id: "60", city: "Rubik", countryId: "1" },
  { _id: "61", city: "Milot", countryId: "1" },
  { _id: "62", city: "Leskovik", countryId: "1" },
  { _id: "63", city: "Konispol", countryId: "1" },
  { _id: "64", city: "Krastë", countryId: "1" },
  { _id: "65", city: "Kërrabë", countryId: "1" },
  { _id: "66", city: "Përmet", countryId: "1" },
  { _id: "67", city: "Skrapar", countryId: "1" },
  { _id: "68", city: "Tropojë", countryId: "1" },
];
export const zones = [
  { _id: "1", zone: "Kombinat", cityId: "1" },
  { _id: "2", zone: "Rruga e Kavajës", cityId: "1" },
  { _id: "3", zone: "Ali Demi", cityId: "1" },
  { _id: "4", zone: "Blloku", cityId: "1" },
  { _id: "5", zone: "Astiri", cityId: "1" },
  { _id: "6", zone: "Brryli", cityId: "1" },
  { _id: "7", zone: "Don Bosko", cityId: "1" },
  { _id: "8", zone: "Himarë", cityId: "1" },
  { _id: "9", zone: "Kamëz", cityId: "1" },
  { _id: "10", zone: "Paskuqan", cityId: "1" },
  { _id: "12", zone: "Komuna e Parisit", cityId: "1" },
  { _id: "13", zone: "Laprakë", cityId: "1" },
  { _id: "14", zone: "Kopshti Botanik", cityId: "1" },
  { _id: "15", zone: "Kopshti Zoologjik", cityId: "1" },
  { _id: "16", zone: "Liqeni i Thatë", cityId: "1" },
  { _id: "17", zone: "Rruga e Durrësit", cityId: "1" },
  { _id: "18", zone: "Stacioni i Trenit", cityId: "1" },
  { _id: "19", zone: "5 Maji", cityId: "1" },
  { _id: "20", zone: "Qyteti Studenti", cityId: "1" },
  { _id: "21", zone: "Sauk i Ri", cityId: "1" },
  { _id: "22", zone: "Sauk i Vjetër", cityId: "1" },
  { _id: "23", zone: "Rolling Hills", cityId: "1" },
  { _id: "24", zone: "Fresku", cityId: "1" },
  { _id: "25", zone: "Currila", cityId: "2" },
  { _id: "26", zone: "Gjiri i Lalëzit", cityId: "2" },
  { _id: "27", zone: "Golem", cityId: "2" },
  { _id: "28", zone: "Shkëmbi i Kavajës", cityId: "2" },
  { _id: "29", zone: "Plepa", cityId: "2" },
  { _id: "30", zone: "Qendër", cityId: "2" },
  { _id: "31", zone: "Zona Periferike", cityId: "2" },
  { _id: "32", zone: "Velipojë", cityId: "3" },
  { _id: "33", zone: "Shirokë", cityId: "3" },
  { _id: "34", zone: "Qendër", cityId: "3" },
  { _id: "35", zone: "Zona Periferike", cityId: "3" },
  { _id: "36", zone: "Qendër", cityId: "20" },
  { _id: "37", zone: "Zona Periferike", cityId: "20" },
];
